language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

matrix:
  exclude:
  - r: devel
    os: osx

install:
  - R -e 'install.packages(c("roxygen2","devtools","TMB","ellipse"),dependencies = TRUE)'
  - make updateStockassessment 

script:
  - make check
  - ls
  - make test

after_succes:
  - cat ./multStockassessment.Rcheck/00check.log
  - cat ./multStockassessment.Rcheck/00install.out

after_failure:
  - cat ./multStockassessment.Rcheck/00check.log
  - cat ./multStockassessment.Rcheck/00install.out
