language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

matrix:
  exclude:
  - r: devel
    os: osx

install:
  - R -e 'install.packages(c("roxygen2","TMB","ellipse"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'
  - make updateStockassessment 

script:
  - make check
  - make test

after_success:
  - ls
  - cat multi_SAM/multStockassessment.Rcheck/00check.log
  - cat calbertsen/multi_SAM/multStockassessment.Rcheck/00install.out

after_failure:
  - ls
  - cat multi_SAM/multStockassessment.Rcheck/00check.log
  - cat calbertsen/multi_SAM/multStockassessment.Rcheck/00install.out
