language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

matrix:
  exclude:
   - os: osx

install:
  - R -e 'install.packages(c("roxygen2"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'
  - make updateStockassessment 

script:
  - make check
  - make install
  - make test

after_success:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out

after_failure:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out
