language: r

sudo: required

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
  global:
    - OS=$(uname -s)

matrix:
  exclude:
  - r: devel
    os: osx

install:
  - R -e 'install.packages(c("roxygen2"),dependencies = c("Depends", "Imports", "LinkingTo", "Enhances"))'
  - if [ ${OS} = Darwin ]; then curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2; fi
  - if [ ${OS} = Darwin ]; then sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C; fi
  - make updateStockassessment 

script:
  - make check
  - make install
  - make test

after_success:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out

after_failure:
  - cat multiStockassessment.Rcheck/00check.log
  - cat multiStockassessment.Rcheck/00install.out
